### PR TITLE
fixed manifest issues

### PR DESCRIPTION
**Pull request by dri94**

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
Nice catch. Thanks for the contribution!

**Comment by dri94** [comment]
hey i dont really know how to contact you @kaloyan-raev besides here. I have a more professional UI i developed for this project. Uses more material design in it. Is this something storj would be interested in? if so is there someway we could discuss this further?

**Comment by kaloyan-raev** [comment]
@dri94 My next step was to completely refactor the UI to follow the Material Design. I haven't started with the coding yet, so it is great that you have something ready or in progress. I'll be happy to take a look at it.

You can open an issue or PR. There we can discuss it and review it. You can also find me in the Storj Community Dev chat: https://community.storj.io/channel/dev

Just to avoid any confusion, I am not affiliated with Storj Labs (the company behind Storj). I just wanted to create an Android project for Storj and started this open source project. I will be happy to collaborate with other enthusiasts like you.

**Comment by dri94** [comment]
Oh i thought you were official storj. Either way I definitely would like to collaborate. I'll be in contact with you soon with a video or images of the app's working. Will need help with registration as i could not find the native code to create accounts though. Everything else from this project is integrated

**Comment by kaloyan-raev** [comment]
libstorj provides a registration function. I haven't exposed it yet in the JNI wrapper, but it won't be a lot of work.

**Comment by dri94** [comment]
messaged on slack to keep github clean

**Pull request merged**
